/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void testAppReternHelloWorld() {
    App classUnderTest = new App();
    assertEquals("Hello World!", classUnderTest.getGreeting());
  }

  @Test
  public void testAppReternCalculate1() {
    App classUnderTest = new App();
    assertEquals("Sum of 2 and 3 is " + sum1 + ". " + "Average is " + String.format("%.1f", ave1)
        + ".", classUnderTest.getGreeting());
  }
}
