/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void testAppReternHelloWorld() {
    App classUnderTest = new App();
    assertEquals("Hello World!", classUnderTest.getGreeting());
  }

  @Test
  public void testAppReternCalculate1() {
    App classUnderTest = new App();
    assertEquals("Sum of 2 and 3 is 5. Average is 2.5.", classUnderTest.calculate1());
  }

  @Test
  public void testAppReternCalculate2() {
    App classUnderTest = new App();
    assertEquals("Sum of 1 to 10 is 55. Average is 5.5.", classUnderTest.calculate2());
  }

  @Test
  public void testAppReternCalculate3() {
    App classUnderTest = new App();
    assertEquals(
        "Sum of odd of 1 to 10 is 25. Sum of even is 30.", classUnderTest.calculate3());
  }
}
