/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Calculate calculate = new Calculate();
        System.out.println(new App().getGreeting());
        int sum1 = calculate.sum(2, 3);
        double ave1 = sum / 2;
        System.out.println("Sum of 2 and 3 is " + sum + "." + "Average is " + String.format("%.1f", ave));
        int sum2 = 0;
        for (i = 1; i <= 10; i++) {
            sum2 =
        }
    }
}
